name: GitHub Actions FE_lvl1
on: [push]
jobs:

  Make-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
      - name: Set up the Node
        uses: actions/setup-node@v1 # Install the "node" software package on the runner to give you access to the "npm" command.

      - name: Install npm
        run: npm i
 
      - name: Make lint
        run: |
          cd ${{ github.workspace }}
          ls Makefile 
          make lint ${{ github.workspace }}


